
import { ContentItem, Fields } from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Wed Nov 14 2018 12:15:24 GMT+0100 (GMT+01:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class. Generator doesn't have this information available
 * and so its up to you to define relationship between models.
 */
export class ReleaseNotes extends ContentItem {
    public newFeatures: Fields.RichTextField;
    public fixedIssues: Fields.RichTextField;
    public apiChanges: Fields.RichTextField;
    public otherNotes: Fields.RichTextField;
    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'new_features') {
                    return 'newFeatures';
                }
                if (fieldName === 'fixed_issues') {
                    return 'fixedIssues';
                }
                if (fieldName === 'api_changes') {
                    return 'apiChanges';
                }
                if (fieldName === 'other_notes') {
                    return 'otherNotes';
                }
                return fieldName;
            })
        });
    }
}
